import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Loader2, ArrowLeft, CheckCircle, XCircle, BrainCircuit } from 'lucide-react';
import { apiFetch } from '../../utils/api';
import './InterviewResults.css';

interface Question {
    id: number;
    question: string;
    options: string[];
    correct_answer: string;
    student_answer: string | null;
    explanation: string;
}

interface Interview {
    id: number;
    job_role_target: string;
    total_score: number;
    ai_feedback: string;
    created_at: string;
}

const InterviewResults = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    
    const [interview, setInterview] = useState<Interview | null>(null);
    const [questions, setQuestions] = useState<Question[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
         const fetchResults = async () => {
            try {
                const data = await apiFetch(`/api/interview/${id}`);
                setInterview(data.interview);
                setQuestions(data.questions || []);
            } catch (error) {
                console.error("Failed to load interview results", error);
                alert("Could not load interview results.");
                navigate('/student/dashboard');
            } finally {
                setLoading(false);
            }
        };
        fetchResults();
    }, [id]);

    if (loading) {
        return (
            <div className="results-loading">
                <Loader2 className="animate-spin text-accent" size={48} />
                <p>Retrieving AI Feedback Report...</p>
            </div>
        );
    }

    if (!interview || !interview.ai_feedback) {
        return (
            <div className="results-container">
                <h2>No Feedback Available</h2>
                <p>This interview might not have been submitted yet.</p>
                <button className="neo-btn-primary mt-4" onClick={() => navigate('/student/dashboard')}>Back to Dashboard</button>
            </div>
        );
    }

    const { total_score, job_role_target, ai_feedback } = interview;
    // Format text paragraphs from AI
    const feedbackParagraphs = ai_feedback.split('\n').filter(p => p.trim() !== '');

    return (
        <motion.div 
            className="results-container"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
        >
            <button className="neo-btn-secondary back-btn" onClick={() => navigate('/student/dashboard')}>
                <ArrowLeft size={18} /> Back to Dashboard
            </button>

            <header className="results-header">
                <div>
                    <h1>Interview Report: {job_role_target}</h1>
                    <p className="text-muted">Generated by AI based on your submitted answers and CV.</p>
                </div>
                <div className={`score-badge ${total_score >= 70 ? 'success' : 'warning'}`}>
                    <span className="score-value">{total_score}%</span>
                    <span className="score-label">Overall Score</span>
                </div>
            </header>

            <div className="results-grid">
                {/* Left Side: AI Feedback Analysis */}
                <div className="feedback-section card">
                    <div className="feedback-title">
                        <BrainCircuit size={24} className="text-accent" />
                        <h2>AI Recruiter Feedback</h2>
                    </div>
                    <div className="feedback-body">
                        {feedbackParagraphs.map((para, i) => (
                            <p key={i}>{para}</p>
                        ))}
                    </div>
                </div>

                {/* Right Side: Detailed Question Breakdown */}
                <div className="breakdown-section card">
                    <h2>Question Breakdown</h2>
                    <div className="questions-review-list">
                        {questions.map((q, idx) => {
                            const isCorrect = q.student_answer?.trim().toLowerCase() === q.correct_answer.trim().toLowerCase();
                            
                            return (
                                <div key={q.id} className={`review-card ${isCorrect ? 'correct-bg' : 'wrong-bg'}`}>
                                    <div className="review-card-header">
                                        <span className="q-number">Q{idx + 1}</span>
                                        {isCorrect ? (
                                            <span className="status-badge success-badge"><CheckCircle size={16}/> Correct</span>
                                        ) : (
                                            <span className="status-badge error-badge"><XCircle size={16}/> Incorrect</span>
                                        )}
                                    </div>
                                    <h4 className="q-text">{q.question}</h4>
                                    
                                    <div className="answers-comparison">
                                        <div className="answer-row">
                                            <span className="label">Your Answer:</span>
                                            <span className={`answer-text ${isCorrect ? 'text-success' : 'text-error'}`}>
                                                {q.student_answer || <em>Not Answered</em>}
                                            </span>
                                        </div>
                                        {!isCorrect && (
                                            <div className="answer-row">
                                                <span className="label">Correct Answer:</span>
                                                <span className="answer-text text-success">{q.correct_answer}</span>
                                            </div>
                                        )}
                                    </div>

                                    {q.explanation && (
                                        <div className="explanation-box">
                                            <strong>Explanation:</strong> {q.explanation}
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        </motion.div>
    );
};

export default InterviewResults;
